### ISSUE TITLE
Chunked encoding

### ISSUE THREAD

**Issue by mikehardenize** [gdwrd/knock#17]
Knock doesn't appear to handle chunked Transfer-Encoding. E.g given the following http response:

```
Content-Type: application/json;charset=UTF-8
Connection: close
Transfer-Encoding: chunked
Date: Fri, 10 Aug 2018 13:42:44 GMT

6
"pong"
0
```

It thinks that the body contains:

```
6
"pong"
0
```

When the body is actually just:

```
"pong"
```

**Comment by mikehardenize** [comment]
For additional information, chunked transfer encoding is required to be supported by HTTP/1.1 clients, but not by HTTP/1.0 clients. I temporarily switched down from 1.1 to 1.0 in my local copy of Knock by changing:

```rust
pub const HTTP_VERSION: &'static str = "HTTP/1.1";
```

To:

```rust
pub const HTTP_VERSION: &'static str = "HTTP/1.0";
```

In `consts.rs`, and that patched over the problem for me.

**Comment by gdwrd** [comment]
You can make PR to downgrade HTTP version or add support for Chunked body.
I don't have much time for working on this project right now. But I can review and apply you PR's.

**Comment by gdwrd** [comment]
Then I can make the new release for crates.io.

**Comment by mikehardenize** [comment]
I've created a PR, so I'll close this issue.

**Comment by gdwrd** [comment]
@mikehardenize I merged all PR's and Publish new release to Crates.io
